version: '2'

services:
  mysqldb:
    container_name: mysqldb
    hostname: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - tarefa_internal
    volumes:
    # Descomentar linha a baixo para manter banco de dados ao finalizar Banco de dados, nescessario descomentar seção de volumes tambem
    #   - my_db:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d

  backend:
    container_name: backend
    depends_on:
      - mysqldb
    build:
      context: ./backend
    image: "python"
    environment:
      - MYSQL_SERVER=${MYSQL_SERVER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TIMEZONE=${TIMEZONE}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    networks:
      - tarefa_internal
      - tarefa
    links:
      - mysqldb

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - tarefa

# volumes:
#   my_db:

networks:
  tarefa:
    external: true
  tarefa_internal: